# Generated by Django 4.2.11 on 2024-03-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_packageorder_packageorderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageorder',
            name='bill',
            field=models.TextField(default=''),
        ),
    ]
