# Generated by Django 4.2.11 on 2024-05-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_orderproduct_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_delivery_man',
            field=models.BooleanField(default=False),
        ),
    ]
