# Generated by Django 4.2.11 on 2024-05-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_is_customer_user_is_delivery_man'),
        ('authentication', '0009_productrating'),
    ]

    operations = [
    ]
