# Generated by Django 4.2.11 on 2024-05-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_merge_20240504_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='otp',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('COOK_READY', 'Cooked Ready'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered')], default='ORDERED', max_length=20),
        ),
        migrations.AddField(
            model_name='packageorder',
            name='otp',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='packageorder',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('COOK_READY', 'Cooked Ready'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered')], default='ORDERED', max_length=20),
        ),
    ]
