# Generated by Django 4.2.11 on 2024-05-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_order_otp_order_status_packageorder_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='otp',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='packageorder',
            name='otp',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
