# Generated by Django 4.2.11 on 2024-05-05 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_order_otp_alter_packageorder_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_product_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packageorder',
            name='delivery_user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_package_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='packageorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_package_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
