# Generated by Django 4.2.11 on 2024-05-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_order_delivery_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('COOK_READY', 'Cooked Ready'), ('ACCEPT', 'Accept'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered')], default='ORDERED', max_length=20),
        ),
        migrations.AlterField(
            model_name='packageorder',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('COOK_READY', 'Cooked Ready'), ('ACCEPT', 'Accept'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered')], default='ORDERED', max_length=20),
        ),
    ]
