# Generated by Django 4.2.11 on 2024-05-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_order_status_alter_packageorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packageorder',
            name='cod',
            field=models.BooleanField(default=False),
        ),
    ]
